# Generated by Django 4.2.4 on 2023-09-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='video',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
