# Generated by Django 4.2.4 on 2023-09-24 21:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsv', '0002_alter_word_description_alter_word_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='video',
            field=models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
